import { ApiProperty, ApiPropertyOptional, PartialType } from '@nestjs/swagger';
import { MedicineStatus } from '@prisma/client';
import { Type } from 'class-transformer';
import {
  IsDateString,
  IsEnum,
  IsInt,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  Min,
} from 'class-validator';
import { PaginationQueryDto } from '../../common/dto/pagination.dto';

export class CreateMedicineDto {
  @ApiProperty({ example: '6221001234567' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(64)
  barcode: string;

  @ApiPropertyOptional({ example: 'MED-0001', description: 'Autogenerated when omitted' })
  @IsOptional()
  @IsString()
  @MaxLength(64)
  sku?: string;

  @ApiProperty({ example: 'Panadol Extra 500mg' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(200)
  name: string;

  @ApiPropertyOptional({ example: 'بنادول اكسترا ٥٠٠ ملغ' })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  nameAr?: string;

  @ApiPropertyOptional({ example: 'Paracetamol + Caffeine' })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  scientificName?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  description?: string;

  @ApiPropertyOptional({ example: 'GSK' })
  @IsOptional()
  @IsString()
  @MaxLength(160)
  manufacturer?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsUUID()
  categoryId?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsUUID()
  supplierId?: string;

  @ApiProperty({ example: 8.5 })
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  purchasePrice: number;

  @ApiProperty({ example: 12.0 })
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  sellingPrice: number;

  @ApiPropertyOptional({ example: 8.5, description: 'Defaults to purchase price' })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  costPrice?: number;

  @ApiPropertyOptional({ example: 15 })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  taxRate?: number;

  @ApiPropertyOptional({ example: 'box', default: 'piece' })
  @IsOptional()
  @IsString()
  @MaxLength(32)
  unit?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  imageUrl?: string;

  @ApiPropertyOptional({ example: 10, default: 10 })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  minStock?: number;
}

export class UpdateMedicineDto extends PartialType(CreateMedicineDto) {
  @ApiPropertyOptional({ enum: MedicineStatus })
  @IsOptional()
  @IsEnum(MedicineStatus)
  status?: MedicineStatus;
}

export class MedicineQueryDto extends PaginationQueryDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsUUID()
  categoryId?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsUUID()
  supplierId?: string;

  @ApiPropertyOptional({ enum: MedicineStatus })
  @IsOptional()
  @IsEnum(MedicineStatus)
  status?: MedicineStatus;

  @ApiPropertyOptional({ description: 'Include per-branch stock for this branch' })
  @IsOptional()
  @IsUUID()
  branchId?: string;
}

export class CreateBatchDto {
  @ApiProperty({ example: 'B-2026-014' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(64)
  batchNumber: string;

  @ApiPropertyOptional({ example: '2025-11-01' })
  @IsOptional()
  @IsDateString()
  manufacturingDate?: string;

  @ApiProperty({ example: '2027-11-01' })
  @IsDateString()
  expiryDate: string;

  @ApiPropertyOptional({ example: 8.5 })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  costPrice?: number;

  @ApiProperty({ example: 100, description: 'Initial quantity received' })
  @Type(() => Number)
  @IsInt()
  @Min(0)
  quantity: number;

  @ApiProperty({ description: 'Branch receiving the stock' })
  @IsUUID()
  branchId: string;
}
