import { PlatformRole, TenantRole } from '@prisma/client';

export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  POS_ACCESS: 'pos.access',
  SALES_VIEW: 'sales.view',
  SALES_CREATE: 'sales.create',
  SALES_RETURN: 'sales.return',
  SALES_VOID: 'sales.void',
  MEDICINES_VIEW: 'medicines.view',
  MEDICINES_MANAGE: 'medicines.manage',
  CATEGORIES_MANAGE: 'categories.manage',
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_COUNT: 'inventory.count',
  INVENTORY_TRANSFER: 'inventory.transfer',
  PURCHASES_VIEW: 'purchases.view',
  PURCHASES_MANAGE: 'purchases.manage',
  SUPPLIERS_VIEW: 'suppliers.view',
  SUPPLIERS_MANAGE: 'suppliers.manage',
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_MANAGE: 'customers.manage',
  ACCOUNTING_VIEW: 'accounting.view',
  ACCOUNTING_MANAGE: 'accounting.manage',
  REPORTS_VIEW: 'reports.view',
  USERS_VIEW: 'users.view',
  USERS_MANAGE: 'users.manage',
  BRANCHES_VIEW: 'branches.view',
  BRANCHES_MANAGE: 'branches.manage',
  SETTINGS_MANAGE: 'settings.manage',
  BILLING_MANAGE: 'billing.manage',
  AUDIT_VIEW: 'audit.view',
  NOTIFICATIONS_VIEW: 'notifications.view',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ALL_TENANT_PERMISSIONS: Permission[] = Object.values(PERMISSIONS);

export const TENANT_ROLE_PERMISSIONS: Record<TenantRole, Permission[]> = {
  [TenantRole.OWNER]: ALL_TENANT_PERMISSIONS,
  [TenantRole.BRANCH_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.POS_ACCESS,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_RETURN,
    PERMISSIONS.SALES_VOID,
    PERMISSIONS.MEDICINES_VIEW,
    PERMISSIONS.MEDICINES_MANAGE,
    PERMISSIONS.CATEGORIES_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_COUNT,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.PURCHASES_MANAGE,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.BRANCHES_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
  [TenantRole.PHARMACIST]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.POS_ACCESS,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_RETURN,
    PERMISSIONS.MEDICINES_VIEW,
    PERMISSIONS.MEDICINES_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
  [TenantRole.CASHIER]: [
    PERMISSIONS.POS_ACCESS,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.MEDICINES_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
  [TenantRole.INVENTORY_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.MEDICINES_VIEW,
    PERMISSIONS.MEDICINES_MANAGE,
    PERMISSIONS.CATEGORIES_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_COUNT,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.PURCHASES_MANAGE,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
  [TenantRole.ACCOUNTANT]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.ACCOUNTING_VIEW,
    PERMISSIONS.ACCOUNTING_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
};

export function permissionsForUser(user: {
  platformRole: PlatformRole | null;
  tenantRole: TenantRole | null;
}): Permission[] {
  if (user.platformRole) {
    return ALL_TENANT_PERMISSIONS;
  }
  if (user.tenantRole) {
    return TENANT_ROLE_PERMISSIONS[user.tenantRole];
  }
  return [];
}
